name: Run Node.js script on a schedule

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Run script
        run: node scripts/compile.js
      - name: Upload
      - run: git add . && git commit -m '[auto] update files' && git push
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
